stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test-pipeline/app
      registry: index.docker.io
- name: publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
