stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./.Dockerfile
      buildContext: .
      tag: test-pipeline/app
      registry: index.docker.io
timeout: 60
notification: {}
