stages:
- name: script
  steps:
  - runScriptConfig:
      image: nginx
      shellScript: |-
        cd /
        ls /etc/nginx
        cd /etc/nginx
        cat nginx.conf
timeout: 60
notification: {}
