kind: Service
apiVersion: v1
metadata:
  name: ng-test-deployment
spec:
  selector:
    app: ngtest
  type: NodePort
  ports:
    - protocol: TCP
      port: 33333
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-test-example
  labels:
    app: ngtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngtest
  template:
    metadata:
      labels:
        app: ngtest
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: ngtest
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80